language: php
php:
  - 8.0
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
env:
  global:
    - MYSQL_TEST_USER=root
    - MYSQL_TEST_PASSWD=
    - MYSQL_TEST_DB=pear_db
    - MYSQL_TEST_HOST=127.0.0.1
matrix:
  include:
    - php: 5.5
      dist: trusty
    - php: 5.4
      dist: trusty
    - php: 5.3
      dist: precise
services:
  - mysql
before_script:
  - mysql -e 'CREATE DATABASE pear_db;'
  - mysql -e 'set global SQL_MODE="NO_ENGINE_SUBSTITUTION";'
script:
  - pear run-tests -r tests/
  - for i in `find tests/ -name '*.out'`; do echo "$i"; cat "$i"; done
